import type { Metadata } from "next";
// Import fonts from next/font/google
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";

// Configure Inter for sans-serif
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // CSS variable for Inter
  display: "swap",
});

// Configure Roboto Mono for monospace
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono", // CSS variable for Roboto Mono
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App", // You can customize this
  description: "Generated by create next app", // You can customize this
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Apply the font variables to the body
        className={`${inter.variable} ${robotoMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
